### ISSUE TITLE
async/await support

### ISSUE THREAD

**Issue by pootzko** [plivo/plivo-dotnet#54]
Hi,

are there any plans to add async/await support to the SDK? 

Thanks

**Comment by pootzko** [comment]
I just looked a bit more into this, and found [this explanation](https://api-reference.plivo.com/latest/net/introduction/request/asynchronous-request) in the docs on how to use async. After that I came back here to take a look at how this is actually implemented because setting "async" as part of the string param seems like an odd way of doing async/await in .net and I found what I suspected I would find. The following [line of code](https://github.com/plivo/plivo-dotnet/blob/c92f8a046fd898da12f91e6843e566052722c97d/src/Plivo/Client/SystemHttpClient.cs#L162) is actually blocking code and this piece of code isn't actually async.

Usage of `.Result` actually produces blocking code. Please see:

- https://montemagno.com/c-sharp-developers-stop-calling-dot-result/
- https://msdn.microsoft.com/en-us/library/dd321468%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396
  > _Accessing the property's get accessor blocks the calling thread until the asynchronous operation is complete; it is equivalent to calling the Wait method._

- https://stackoverflow.com/questions/41327052/does-net-task-result-blocksynchronously-a-thread
- https://stackoverflow.com/questions/12484112/what-happens-while-waiting-on-a-tasks-result

**Comment by plivo-sdks** [comment]
@pootzko The asynchronous request mentioned in Plivo docs are not the async requests you are looking for (they are async in the sense that the processing takes place on our servers the then the results are posted to a callback URL you provide).

Talking about the line of code you pointed to, the initial plan was to use `await` instead of `.Result`, but we had to push that feature for a future release as we wanted to design the SDK interfaces in a neater manner to be able to support async. We don't have an ETA on this feature yet.

Answering your initial question, nope, the current .NET SDK doesn't support async requests yet.

**Comment by huzaif-plivo** [comment]
@pootzko This feature has been added. You can try our latest version of 4.4.3 :)
